package datamanagement;

import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

public class ChangeGradeInterface extends javax.swing.JFrame implements IUnitLister,
		IStudentLister {
	private ChangeGradeControl control;//studentcomboboxmode 
	private javax.swing.DefaultComboBoxModel unitComboBoxModel;
	private javax.swing.DefaultComboBoxModel studentComboBoxModel;
	float assignment1Mark;
	float assignment2Mark;
	float examMark;
	Integer studentId;

	public ChangeGradeInterface(ChangeGradeControl control) {
		this.control = control;
		unitComboBoxModel = new javax.swing.DefaultComboBoxModel(new String[0]);
		studentComboBoxModel = new javax.swing.DefaultComboBoxModel(new String[0]);
		initializeComponents();
		unitComboBox.setModel(unitComboBoxModel);
		studentComboBox.setModel(studentComboBoxModel);
		errorLabel.setText("");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initializeComponents() {

		mainPanelLabel = new javax.swing.JLabel();
		unitPanel = new javax.swing.JPanel();
		unitComboBox = new javax.swing.JComboBox();
		studentPanel = new javax.swing.JPanel();
		studentComboBox = new javax.swing.JComboBox();
		marksPanel = new javax.swing.JPanel();
		assignment1Label = new javax.swing.JLabel();
		assignment2Label = new javax.swing.JLabel();
		examLabel = new javax.swing.JLabel();
		assignment1Text = new javax.swing.JTextField();
		assignment2Text = new javax.swing.JTextField();
		examText = new javax.swing.JTextField();
		changeButton = new javax.swing.JButton();
		gradePanel = new javax.swing.JPanel();
		gradeLabel = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		mainPanelLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
		mainPanelLabel.setText("Check Grade UI");

		unitPanel.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Unit"));

		unitComboBox.setModel(unitComboBoxModel);
		unitComboBox.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent event) {
				unitComboBoxItemStateChanged(event);
			}
		});

		javax.swing.GroupLayout gl_unitPanel = new javax.swing.GroupLayout(
				unitPanel);
		unitPanel.setLayout(gl_unitPanel);
		gl_unitPanel.setHorizontalGroup(gl_unitPanel.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				gl_unitPanel
						.createSequentialGroup()
						.addContainerGap()
						.addComponent(unitComboBox,
								javax.swing.GroupLayout.PREFERRED_SIZE, 185,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		gl_unitPanel.setVerticalGroup(gl_unitPanel.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				gl_unitPanel
						.createSequentialGroup()
						.addComponent(unitComboBox,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		studentPanel.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Student"));

		studentComboBox.setModel(studentComboBoxModel);
		studentComboBox.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent event) {
				studentComboBoxItemStateChanged(event);
			}
		});

		javax.swing.GroupLayout gl_studentPanel = new javax.swing.GroupLayout(
				studentPanel);
		studentPanel.setLayout(gl_studentPanel);
		gl_studentPanel.setHorizontalGroup(gl_studentPanel.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				gl_studentPanel
						.createSequentialGroup()
						.addContainerGap()
						.addComponent(studentComboBox,
								javax.swing.GroupLayout.PREFERRED_SIZE, 185,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		gl_studentPanel.setVerticalGroup(gl_studentPanel.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				gl_studentPanel
						.createSequentialGroup()
						.addComponent(studentComboBox,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		marksPanel.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Marks"));

		assignment1Label.setText("Asg1:");

		assignment2Label.setText("Asg2:");

		examLabel.setText("Exam:");

		assignment1Text.setEditable(false);
		assignment1Text.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent event) {
				jTextFieldKeyTyped(event);
			}
		});

		assignment2Text.setEditable(false);
		assignment2Text.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent event) {
				jTextFieldKeyTyped(event);
			}
		});

		examText.setEditable(false);
		examText.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent event) {
				jTextFieldKeyTyped(event);
			}
		});

		changeButton.setText("Change");
		changeButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent event) {
				changeButtonActionPerformed(event);
			}
		});
		checkGradeButton = new javax.swing.JButton();

		checkGradeButton.setText("Check Grade");
		checkGradeButton.setActionCommand("checkGrade");
		checkGradeButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent event) {
				saveButtonActionPerformed(event);
			}
		});

		javax.swing.GroupLayout gl_marksPanel = new javax.swing.GroupLayout(
				marksPanel);
		gl_marksPanel
				.setHorizontalGroup(gl_marksPanel
						.createParallelGroup(Alignment.LEADING)
						.addGroup(
								gl_marksPanel
										.createSequentialGroup()
										.addGroup(
												gl_marksPanel
														.createParallelGroup(
																Alignment.LEADING)
														.addGroup(
																gl_marksPanel
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				assignment1Label)
																		.addPreferredGap(
																				ComponentPlacement.RELATED)
																		.addComponent(
																				assignment1Text,
																				GroupLayout.PREFERRED_SIZE,
																				59,
																				GroupLayout.PREFERRED_SIZE)
																		.addGap(18)
																		.addComponent(
																				assignment2Label))
														.addGroup(
																gl_marksPanel
																		.createSequentialGroup()
																		.addGap(85)
																		.addComponent(
																				changeButton,
																				GroupLayout.PREFERRED_SIZE,
																				84,
																				GroupLayout.PREFERRED_SIZE)))
										.addGap(18)
										.addGroup(
												gl_marksPanel
														.createParallelGroup(
																Alignment.TRAILING)
														.addGroup(
																gl_marksPanel
																		.createSequentialGroup()
																		.addComponent(
																				assignment2Text,
																				GroupLayout.PREFERRED_SIZE,
																				59,
																				GroupLayout.PREFERRED_SIZE)
																		.addGap(18)
																		.addComponent(
																				examLabel))
														.addComponent(
																checkGradeButton))
										.addGap(18)
										.addComponent(examText,
												GroupLayout.PREFERRED_SIZE, 59,
												GroupLayout.PREFERRED_SIZE)
										.addGap(15)));
		gl_marksPanel
				.setVerticalGroup(gl_marksPanel
						.createParallelGroup(Alignment.LEADING)
						.addGroup(
								gl_marksPanel
										.createSequentialGroup()
										.addGroup(
												gl_marksPanel
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(
																assignment1Label)
														.addComponent(
																assignment1Text,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(
																assignment2Label)
														.addComponent(
																assignment2Text,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(examLabel)
														.addComponent(
																examText,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												ComponentPlacement.UNRELATED)
										.addGroup(
												gl_marksPanel
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(
																changeButton)
														.addComponent(
																checkGradeButton))
										.addContainerGap()));
		marksPanel.setLayout(gl_marksPanel);

		gradePanel.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Grade"));

		gradeLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		gradeLabel.setForeground(new java.awt.Color(255, 0, 0));
		gradeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		gradeLabel.setText("grade");

		javax.swing.GroupLayout gl_gradePanel = new javax.swing.GroupLayout(
				gradePanel);
		gradePanel.setLayout(gl_gradePanel);
		gl_gradePanel.setHorizontalGroup(gl_gradePanel.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				gradeLabel, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE));
		gl_gradePanel.setVerticalGroup(gl_gradePanel.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				gl_gradePanel.createSequentialGroup().addGap(34, 34, 34)
						.addComponent(gradeLabel)
						.addContainerGap(43, Short.MAX_VALUE)));

		errorLabel = new JLabel();
		errorLabel.setText("Error message");
		errorLabel.setForeground(Color.RED);
		errorLabel.setFont(new Font("Tahoma", Font.PLAIN, 12));
		saveButton = new javax.swing.JButton();

		saveButton.setText("Save");
		saveButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent event) {
				checkGradeButtonActionPerformed(event);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(layout
				.createParallelGroup(Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		errorLabel,
																		GroupLayout.DEFAULT_SIZE,
																		400,
																		Short.MAX_VALUE))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.LEADING,
																				false)
																				.addComponent(
																						marksPanel,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												Alignment.LEADING)
																												.addComponent(
																														unitPanel,
																														GroupLayout.PREFERRED_SIZE,
																														GroupLayout.DEFAULT_SIZE,
																														GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														studentPanel,
																														GroupLayout.PREFERRED_SIZE,
																														GroupLayout.DEFAULT_SIZE,
																														GroupLayout.PREFERRED_SIZE))
																								.addGap(18)
																								.addComponent(
																										gradePanel,
																										GroupLayout.PREFERRED_SIZE,
																										GroupLayout.DEFAULT_SIZE,
																										GroupLayout.PREFERRED_SIZE))))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(157)
																.addComponent(
																		mainPanelLabel))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(165)
																.addComponent(
																		saveButton,
																		GroupLayout.PREFERRED_SIZE,
																		86,
																		GroupLayout.PREFERRED_SIZE)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(mainPanelLabel)
								.addGap(13)
								.addGroup(
										layout.createParallelGroup(
												Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		unitPanel,
																		GroupLayout.PREFERRED_SIZE,
																		GroupLayout.DEFAULT_SIZE,
																		GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		ComponentPlacement.RELATED)
																.addComponent(
																		studentPanel,
																		GroupLayout.PREFERRED_SIZE,
																		GroupLayout.DEFAULT_SIZE,
																		GroupLayout.PREFERRED_SIZE))
												.addComponent(
														gradePanel,
														GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE,
														GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(ComponentPlacement.RELATED,
										GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(marksPanel,
										GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(saveButton)
								.addGap(11)
								.addComponent(errorLabel,
										GroupLayout.PREFERRED_SIZE, 30,
										GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void unitComboBoxItemStateChanged(java.awt.event.ItemEvent event) {// GEN-FIRST:event_jComboBox1ItemStateChanged
		String changeUnit = (String) unitComboBox.getSelectedItem();
		Refresh3();
		clearStudents();
		if (event.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
			if (changeUnit.equals((String) unitComboBox.getItemAt(0))) {
				changeUnit = "NONE";
			}
			control.unitSelected(changeUnit);
		}
	}// GEN-LAST:event_jComboBox1ItemStateChanged

	private void studentComboBoxItemStateChanged(java.awt.event.ItemEvent event) {// GEN-FIRST:event_jComboBox2ItemStateChanged
		Refresh3();
		String changeStudent = (String) studentComboBox.getSelectedItem();
		if (event.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
			if (changeStudent.equals((String) studentComboBox.getItemAt(0))) {
				studentId = new Integer(0);
				control.studentSelected(studentId);
			} else {
				studentId = new Integer(changeStudent.split("\\s")[0]);
			}
			control.studentSelected(studentId);
		}
	}// GEN-LAST:event_jComboBox2ItemStateChanged

	private void saveButtonActionPerformed(java.awt.event.ActionEvent event) {// GEN-FIRST:event_saveButtonActionPerformed
		assignment1Mark = new Float(assignment1Text.getText()).floatValue();
		assignment2Mark = new Float(assignment2Text.getText()).floatValue();
		examMark = new Float(examText.getText()).floatValue();
		// lblErrMsg.setText("");
		try {
			String student = control.checkGrade(assignment1Mark, assignment2Mark, examMark);
			gradeLabel.setText(student);
		} catch (RuntimeException runtimeExeption) {
			errorLabel.setText(runtimeExeption.getMessage());
		}
	}// GEN-LAST:event_saveButtonActionPerformed

	private void changeButtonActionPerformed(java.awt.event.ActionEvent event) {// GEN-FIRST:event_changeButtonActionPerformed
		control.enableChangeMarks();
		gradeLabel.setText("");
		// lblErrMsg.setText("");
	}// GEN-LAST:event_changeButtonActionPerformed

	private void jTextFieldKeyTyped(java.awt.event.KeyEvent event) {// GEN-FIRST:event_jTextField1KeyTyped
		gradeLabel.setText("");
		errorLabel.setText("");
	}// GEN-LAST:event_jTextField1KeyTyped

	private void checkGradeButtonActionPerformed(java.awt.event.ActionEvent event) {// GEN-FIRST:event_checkGradeButtonActionPerformed
		float assignment1 = new Float(assignment1Text.getText()).floatValue();
		float assignment2 = new Float(assignment2Text.getText()).floatValue();
		float exam = new Float(examText.getText()).floatValue();
		errorLabel.setText("");
		try {
			control.saveGrade(assignment1, assignment2, exam);
			// saveButtonActionPerformed(null);
		} catch (RuntimeException runtimeExeption) {
			errorLabel.setText(runtimeExeption.getMessage());
		}
	}// GEN-LAST:event_checkGradeButtonActionPerformed

	public void clearUnits() {
		unitComboBoxModel.removeAllElements();
		unitComboBoxModel.addElement("<none selected>");
		clearStudents();
	}

	public void addUnit(IUnit unit) {
		unitComboBoxModel.addElement(unit.getUnitCode());
	}

	public void setState1(boolean b) {
		unitComboBox.setEnabled(b);
		errorLabel.setText("");
	}

	public void clearStudents() {
		studentComboBoxModel.removeAllElements();
		studentComboBoxModel.addElement("<none selected>");
	}

	public void addStudent(IStudent student) {
		studentComboBoxModel.addElement(student.getId().toString() + " : " + student.getFirstName() + " " + student.getLastName());
	}

	public void setState2(boolean b) {
		studentComboBox.setEnabled(b);
		errorLabel.setText("");
	}

	public void setRecord(IStudentUnitRecord record) {
		assignment1Text.setText(new Float(record.getAssignment1()).toString());
		assignment2Text.setText(new Float(record.getAssignment2()).toString());
		examText.setText(new Float(record.getExam()).toString());
		gradeLabel.setText("");
	}

	public void Refresh3() {
		assignment1Text.setText("");
		assignment2Text.setText("");
		examText.setText("");
		gradeLabel.setText("");
		errorLabel.setText("");
		assignment1Text.setEditable(false);
		assignment2Text.setEditable(false);
		examText.setEditable(false);
	}

	public void setState3(boolean b) {
		checkGradeButton.setEnabled(b);
	}

	public void setState4(boolean b) {
		changeButton.setEnabled(b);
		// gradeLB.setText("");
	}

	public void setState5(boolean b) {
		assignment1Text.setEditable(b);
		assignment2Text.setEditable(b);
		examText.setEditable(b);
	}

	public void setState6(boolean b) {
		saveButton.setEnabled(b);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton changeButton;
	private javax.swing.JButton checkGradeButton;
	private javax.swing.JButton saveButton;
	private javax.swing.JComboBox unitComboBox;
	private javax.swing.JComboBox studentComboBox;
	private javax.swing.JLabel mainPanelLabel;
	private javax.swing.JLabel assignment1Label;
	private javax.swing.JLabel assignment2Label;
	private javax.swing.JLabel examLabel;
	private javax.swing.JLabel gradeLabel;
	private javax.swing.JLabel errorLabel;
	private javax.swing.JPanel unitPanel;
	private javax.swing.JPanel studentPanel;
	private javax.swing.JPanel marksPanel;
	private javax.swing.JPanel gradePanel;
	private javax.swing.JTextField assignment1Text;
	private javax.swing.JTextField assignment2Text;
	private javax.swing.JTextField examText;
}
